// angular-groups-list/src/lib/components/groups-list/groups-list.component.ts
import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { Group } from '../../models/group';
import { Lector } from '../../models/lector';
import { GroupDetails } from '../../models/group-details';
import { Filter } from '../../models/filter';
import { FilterTabs } from '../../enums/filter-tabs';
import { GroupSortType } from '../../enums/group-sort-type';
import { ListDisplayType } from '../../enums/list-display-type';
import { ModalType } from '../../enums/modal-type';
import { SpecialGroup } from '../../models/special-group';
import { GroupsApiService } from '../../services/groups-api.service';
import { GroupService } from '../../services/group.service';

@Component({
  selector: 'dante-groups-list',
  template: `
    <div class="groups-list-container">
      
      <!-- Filter and Sort Controls (simplified for now) -->
      <div class="controls">
        <div class="display-type-toggle">
          <button 
            [class.active]="selectedListDisplayType === listDisplayTypeEnum.Grid"
            (click)="setDisplayType(listDisplayTypeEnum.Grid)">
            Grid
          </button>
          <button 
            [class.active]="selectedListDisplayType === listDisplayTypeEnum.List"
            (click)="setDisplayType(listDisplayTypeEnum.List)">
            Table
          </button>
        </div>
        
        <div class="sort-controls">
          <label for="sortSelect">Sort by:</label>
          <select id="sortSelect" [(ngModel)]="selectedSortType" (ngModelChange)="onSortChange()">
            <option [value]="groupSortTypeEnum.Level">Level</option>
            <option [value]="groupSortTypeEnum.Day">Day</option>
            <option [value]="groupSortTypeEnum.StartDate">Start Date</option>
            <option [value]="groupSortTypeEnum.Lector">Lector</option>
          </select>
        </div>
      </div>

      <!-- Groups Display -->
      <div class="groups-content">
        
        <!-- Table View -->
        <dante-groups-table 
          *ngIf="selectedListDisplayType === listDisplayTypeEnum.List"
          [groups]="filteredGroups"
          (onShowGroupDetails)="onShowGroupDetails($event)"
          (onShowSignIn)="onShowSignIn($event)"
          (onShowNotify)="onShowNotify($event)">
        </dante-groups-table>
        
        <!-- Grid View -->
        <div *ngIf="selectedListDisplayType === listDisplayTypeEnum.Grid" class="group-list">
          <dante-group-card
            *ngFor="let group of filteredGroups; trackBy: trackByGroupId"
            [group]="group"
            (onShowGroupDetails)="onShowGroupDetails($event)"
            (onShowSignIn)="onShowSignIn($event)"
            (onShowNotify)="onShowNotify($event)">
          </dante-group-card>
        </div>
        
      </div>
      
      <!-- Modal Manager -->
      <dante-modal-manager
        *ngIf="modalType !== modalTypeEnum.None"
        [groupDetails]="groupDetails"
        [group]="selectedGroup"
        [modalType]="modalType"
        [isGroupDetailsOpen]="isGroupDetailsOpen"
        (onCloseModal)="closeModals()"
        (onShowSignIn)="onShowSignIn($event)"
        (onShowNotify)="onShowNotify($event)">
      </dante-modal-manager>
      
    </div>
  `,
  styleUrls: ['./groups-list.component.css']
})
export class GroupsListComponent implements OnInit, OnChanges {
  @Input() groups: Group[] = [];
  @Input() lectors: Lector[] = [];

  filteredGroups: Group[] = [];
  selectedGroup: Group | null = null;
  groupDetails: GroupDetails | null = null;
  isGroupDetailsOpen = false;
  modalType = ModalType.None;
  selectedFilterTab = FilterTabs.None;
  selectedSortType = GroupSortType.Level;
  selectedListDisplayType = ListDisplayType.Grid;
  
  // Enum references for template
  modalTypeEnum = ModalType;
  listDisplayTypeEnum = ListDisplayType;
  groupSortTypeEnum = GroupSortType;

  filter: Filter = {
    groupDays: [],
    groupLector: [],
    groupLevel: [],
    groupType: [],
    groupPeriod: [],
    groupState: [],
  };

  constructor(
    private groupsApiService: GroupsApiService,
    private groupService: GroupService
  ) {}

  ngOnInit(): void {
    this.updateFilteredGroups();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['groups']) {
      this.updateFilteredGroups();
    }
  }

  trackByGroupId(index: number, group: Group): string {
    return group.groupId;
  }

  setDisplayType(type: ListDisplayType): void {
    this.selectedListDisplayType = type;
  }

  onSortChange(): void {
    this.updateFilteredGroups();
  }

  private updateFilteredGroups(): void {
    let filtered = [...this.groups];
    
    // Apply sorting
    filtered = this.sortGroups(filtered);
    
    this.filteredGroups = filtered;
  }

  private sortGroups(groups: Group[]): Group[] {
    return groups.sort((a, b) => {
      switch (this.selectedSortType) {
        case GroupSortType.Level:
          return a.groupLevel.localeCompare(b.groupLevel);
        
        case GroupSortType.Day:
          const aDayNum = this.groupService.dayMappingToNumber[a.groupDays.split('-')[0]] || 8;
          const bDayNum = this.groupService.dayMappingToNumber[b.groupDays.split('-')[0]] || 8;
          return aDayNum - bDayNum;
        
        case GroupSortType.StartDate:
          return this.groupService.parseDateToNumber(a.groupFirstMeet) - 
                 this.groupService.parseDateToNumber(b.groupFirstMeet);
        
        case GroupSortType.Lector:
          return a.groupLector.localeCompare(b.groupLector);
        
        default:
          return 0;
      }
    });
  }

  private async fetchGroupDetails(groupId: string): Promise<void> {
    const group = this.groups.find((group) => group.groupId === groupId) ?? null;

    if (group && group instanceof SpecialGroup) {
      this.groupDetails = group.details;
      return;
    }

    this.selectedGroup = group;
    
    this.groupsApiService.fetchGroup(groupId).subscribe({
      next: (data) => {
        this.groupDetails = data;
      },
      error: (error) => {
        console.error('Error fetching group details:', error);
        this.groupDetails = null;
      }
    });
  }

  closeModals(): void {
    this.isGroupDetailsOpen = false;
    this.modalType = ModalType.None;
    this.groupDetails = null;
  }

  async onShowGroupDetails(groupId: string): Promise<void> {
    await this.fetchGroupDetails(groupId);
    this.isGroupDetailsOpen = true;
    this.modalType = ModalType.Details;
  }

  async onShowSignIn(groupId: string): Promise<void> {
    await this.fetchGroupDetails(groupId);
    this.modalType = ModalType.SignIn;
  }

  async onShowNotify(groupId: string): Promise<void> {
    await this.fetchGroupDetails(groupId);
    this.modalType = ModalType.Notify;
  }
}

// src/groups-list/GroupsList.tsx
import { useEffect, useState } from "react";
import { GroupCard } from "../group-card/GroupCard";
import { GroupsFilter } from "../group-filter/GroupsFilter";
import { Group } from "../models/group";
import { Filter } from "../models/filter";
import {
  dayMappingToNumber,
  mapGroupHoursToPeriod,
  parseDateToNumber,
} from "../services/group-service";
import { GroupDetails } from "../models/group-details";
import { FilterTabs } from "../enums/filter-tabs";
import { GroupSort } from "../group-sort/GroupSort";
import { GroupSortType } from "../enums/group-sort-type";

import styles from "./GroupsList.module.css";
import { ListDisplayType } from "../enums/list-display-type";
import { GroupsTable } from "../groups-table/GroupsTable";
import { fetchGroup } from "../api/groups-api";
import { SpecialGroup } from "../models/special-group";
import { ModalManager } from "../modal-manager/ModalManager";
import { ModalType } from "../enums/modal-type";
import { Lector } from "../models/lector";

export const GroupsList = ({ groups, lectors }: { groups: Group[], lectors: Lector[] }) => {
  const [filteredGroups, setFilteredGroups] = useState<Group[]>(groups);
  const [groupDetails, setGroupDetails] = useState<GroupDetails | null>(null);
  const [isGroupDetailsOpen, setIsGroupDetailsOpen] = useState(false);
  const [modalType, setModalType] = useState<ModalType>(ModalType.None);
  const [selectedFilterTab, setSelectedFilterTab] = useState(FilterTabs.None);
  const [selectedSortType, setSelectedSortType] = useState<GroupSortType>(
    GroupSortType.Level
  );
  const [selectedListDisplayType, setSelectedListDisplayType] =
    useState<ListDisplayType>(ListDisplayType.Grid);
  const [filter, setFilter] = useState<Filter>({
    groupDays: [],
    groupLector: [],
    groupLevel: [],
    groupType: [],
    groupPeriod: [],
    groupState: [],
  });

  useEffect(() => {
    sort(GroupSortType.Level, groups);
  }, [groups]);

  const filterGroups = (filter: Filter) => {
    let filteredGroups = groups;

    if (filter.groupType.length > 0) {
      filteredGroups = filteredGroups.filter(
        (group) =>
          filter.groupType.includes(group.groupType) || group.groupAlwaysVisible
      );
    }

    if (filter.groupLevel.length > 0) {
      filteredGroups = filteredGroups.filter(
        (group) =>
          filter.groupLevel.includes(group.groupLevel) ||
          group.groupAlwaysVisible
      );
    }

    if (filter.groupDays.length > 0) {
      filteredGroups = filteredGroups.filter((group) =>
        filter.groupDays.some(
          (day) =>
            group.groupDays.split("-").includes(day as string) ||
            group.groupAlwaysVisible
        )
      );
    }

    if (filter.groupLector.length > 0) {
      filteredGroups = filteredGroups.filter(
        (group) =>
          filter.groupLector.includes(group.groupLector) ||
          group.groupAlwaysVisible
      );
    }

    if (filter.groupPeriod.length > 0) {
      filteredGroups = filteredGroups.filter(
        (group) =>
          filter.groupPeriod.includes(
            mapGroupHoursToPeriod(group.groupHours)
          ) || group.groupAlwaysVisible
      );
    }

    if (filter.groupState.length > 0) {
      filteredGroups = filteredGroups.filter(
        (group) =>
          filter.groupState.includes(group.groupState) ||
          group.groupAlwaysVisible
      );
    }

    sort(selectedSortType, filteredGroups);
  };

  const fetchGroupDetails = async (groupId: string) => {
    const group = groups.find((group) => group.groupId === groupId);

    if (group && group instanceof SpecialGroup) {
      setGroupDetails(group.details);
      return;
    }

    const data = await fetchGroup(groupId);
    setGroupDetails(data);
  };

  const closeModals = () => {
    setIsGroupDetailsOpen(false);
    setModalType(ModalType.None);
    setGroupDetails(null);
  };

  const onShowGroupDetails = async (groupId: string) => {
    await fetchGroupDetails(groupId);
    setIsGroupDetailsOpen(true);
    setModalType(ModalType.Details);
  };

  const onShowSignIn = async (groupId: string) => {
    await fetchGroupDetails(groupId);
    setModalType(ModalType.SignIn);
  };

  const onShowNotify = async (groupId: string) => {
    await fetchGroupDetails(groupId);
    setModalType(ModalType.Notify);
  };

  const onToggleFilterTab = (tab: FilterTabs) => {
    if (selectedFilterTab === tab) {
      setSelectedFilterTab(FilterTabs.None);
    } else {
      setSelectedFilterTab(tab);
    }
  };

  const onToggleSort = (type: GroupSortType) => {
    let sortBy = GroupSortType.Level;

    if (selectedSortType === type) {
      setSelectedSortType(GroupSortType.Level);
    } else {
      setSelectedSortType(type);
      sortBy = type;
    }

    sort(sortBy, filteredGroups);
  };

  const sort = (sortBy: GroupSortType, groupsToSort: Group[]) => {
    let sortedGroups: Group[] = [];
    const specialGroups = groupsToSort.filter(
      (group) => group instanceof SpecialGroup
    );
    const nonSpecialGroups = groupsToSort.filter(
      (group) => !(group instanceof SpecialGroup)
    );
    switch (sortBy) {
      case GroupSortType.Level:
        sortedGroups =
          [...nonSpecialGroups].sort((a, b) =>
            a.groupShortName.localeCompare(b.groupShortName)
          );
        break;
      case GroupSortType.Day:
        sortedGroups =
          [...nonSpecialGroups].sort(
            (a, b) =>
              dayMappingToNumber[a.groupDays.split("-")[0]] -
              dayMappingToNumber[b.groupDays.split("-")[0]]
          );
        break;
      case GroupSortType.StartDate:
        sortedGroups =
          [...nonSpecialGroups].sort(
            (a, b) =>
              parseDateToNumber(a.groupFirstMeet) -
              parseDateToNumber(b.groupFirstMeet)
          );
        break;
      case GroupSortType.Lector:
        sortedGroups =
          [...nonSpecialGroups].sort((a, b) =>
            a.groupLector.localeCompare(b.groupLector)
          );
        break;
    }
    setFilteredGroups([...sortedGroups, ...specialGroups]);
  };

  return (
    <div className={styles.listContainer}>
      <div className={styles.toolbar}>
        <div
          className={styles.toolbarItem}
          onClick={() => onToggleFilterTab(FilterTabs.Filters)}
        >
          <span className="material-symbols-outlined">tune</span>
          Filtry
        </div>
        <div
          className={styles.toolbarItem}
          onClick={() => onToggleFilterTab(FilterTabs.Sort)}
        >
          <span className="material-symbols-outlined">swap_vert</span>
          Sortuj
        </div>
        <div className={styles.displayTypeContainer}>
          <div
            className={`${styles.displayTypeItem} ${selectedListDisplayType === ListDisplayType.Grid
              ? styles.selected
              : ""
              }`}
            onClick={() => setSelectedListDisplayType(ListDisplayType.Grid)}
          >
            Kafelki
          </div>
          <div
            className={`${styles.displayTypeItem} ${selectedListDisplayType === ListDisplayType.List
              ? styles.selected
              : ""
              }`}
            onClick={() => setSelectedListDisplayType(ListDisplayType.List)}
          >
            Lista
          </div>
        </div>
      </div>
      <div className={styles.toolbarTab}>
        {selectedFilterTab === FilterTabs.Filters && (
          <div className={styles.filters}>
            <GroupsFilter
              groups={groups}
              filterGroups={filterGroups}
              handleSetFilter={setFilter}
              filter={filter}
              lectors={lectors}
            />
          </div>
        )}
        {selectedFilterTab === FilterTabs.Sort && (
          <div className={styles.sort}>
            <GroupSort
              onSortChange={onToggleSort}
              sortType={selectedSortType}
            ></GroupSort>
          </div>
        )}
      </div>
      <div className={`${styles.filters} ${styles.filtersMobile}`}>
        <GroupsFilter
          groups={groups}
          filterGroups={filterGroups}
          handleSetFilter={setFilter}
          filter={filter}
          lectors={lectors}
        />
      </div>

      <div className={styles.groupsListContainer}>
        {filteredGroups.length === 0 ? (
          <div className={styles.noGroups}>
            Brak grup dla wybranych kryteriów
          </div>
        ) : selectedListDisplayType === ListDisplayType.List ? (
          <GroupsTable
            groups={filteredGroups}
            onShowGroupDetails={onShowGroupDetails}
            onShowSignIn={onShowSignIn}
            onShowNotify={onShowNotify}
          ></GroupsTable>
        ) : (
          <div className={styles.groupList}>
            {filteredGroups.map((group) => (
              <GroupCard
                group={group}
                onShowGroupDetails={onShowGroupDetails}
                onShowSignIn={onShowSignIn}
                onShowNotify={onShowNotify}
                key={group.groupId}
              />
            ))}
          </div>
        )}
      </div>
      <ModalManager
        groupDetails={groupDetails}
        onCloseModal={closeModals}
        modalType={modalType}
        isGroupDetailsOpen={isGroupDetailsOpen}
        onShowSignIn={onShowSignIn}
        onShowNotify={onShowNotify}
      />
    </div>
  );
};
