// angular-groups-list/src/lib/components/groups-table/groups-table.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Group } from '../../models/group';
import { GroupService } from '../../services/group.service';

type SortColumn = 'level' | 'day' | 'hour' | 'lector' | 'type' | null;
type SortDirection = 'asc' | 'desc' | null;

@Component({
  selector: 'dante-groups-table',
  template: `
    <div class="table-container">
      <table class="groups-table">
        <thead>
          <tr>
            <th (click)="handleSort('level')" [class.sortable]="true">
              Poziom
              <span *ngIf="sortColumn === 'level'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th (click)="handleSort('day')" [class.sortable]="true">
              Dzień
              <span *ngIf="sortColumn === 'day'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th (click)="handleSort('hour')" [class.sortable]="true">
              Godzina
              <span *ngIf="sortColumn === 'hour'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th (click)="handleSort('lector')" [class.sortable]="true">
              Lektor
              <span *ngIf="sortColumn === 'lector'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th (click)="handleSort('type')" [class.sortable]="true">
              Typ
              <span *ngIf="sortColumn === 'type'" class="sort-indicator">
                {{ sortDirection === 'asc' ? '↑' : '↓' }}
              </span>
            </th>
            <th>Akcje</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let group of getSortedGroups(); trackBy: trackByGroupId" 
              [class.full-group]="group.groupFreePlaces === 0">
            
            <td class="level">{{ group.groupShortName }}</td>
            
            <td class="day">
              {{ group.groupDays ? getFormattedGroupDays(group.groupDays) : '-' }}
            </td>
            
            <td class="hour">
              {{ group.groupHours ? getFormattedGroupHours(group.groupHours) : '-' }}
            </td>
            
            <td class="lector">{{ group.groupLector }}</td>
            
            <td class="type">
              <div class="type-content">
                <div class="lector">{{ group.groupLector }}</div>
                <div class="type-indicator">
                  <div class="icon" *ngIf="group.groupType === 'stacjonarna'">
                    <span class="material-symbols-outlined">home</span>
                  </div>
                  <div class="icon" *ngIf="group.groupType !== 'stacjonarna'">
                    <span class="material-symbols-outlined">computer</span>
                  </div>
                </div>
              </div>
            </td>
            
            <td class="actions">
              <div class="icon info-icon" (click)="onShowGroupDetails.emit(group.groupId)">
                <span class="material-symbols-outlined">info</span>
              </div>
              
              <div *ngIf="group.groupFreePlaces === 0; else signInButton"
                   class="sign-in-btn dante-button sign-in"
                   (click)="onShowNotify.emit(group.groupId)">
                Powiadom mnie
              </div>
              
              <ng-template #signInButton>
                <div class="sign-in-btn dante-button sign-in"
                     (click)="onShowSignIn.emit(group.groupId)">
                  Zapisz się
                </div>
              </ng-template>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  `,
  styleUrls: ['./groups-table.component.css']
})
export class GroupsTableComponent {
  @Input() groups: Group[] = [];
  
  @Output() onShowGroupDetails = new EventEmitter<string>();
  @Output() onShowSignIn = new EventEmitter<string>();
  @Output() onShowNotify = new EventEmitter<string>();

  sortColumn: SortColumn = null;
  sortDirection: SortDirection = null;

  constructor(private groupService: GroupService) {}

  trackByGroupId(index: number, group: Group): string {
    return group.groupId;
  }

  handleSort(column: SortColumn): void {
    if (this.sortColumn === column) {
      if (this.sortDirection === 'desc') {
        this.sortDirection = 'asc';
      } else if (this.sortDirection === 'asc') {
        this.sortDirection = null;
        this.sortColumn = null;
      } else {
        this.sortDirection = 'desc';
      }
    } else {
      this.sortColumn = column;
      this.sortDirection = 'desc';
    }
  }

  getSortedGroups(): Group[] {
    const regularGroups = this.groups.filter(group => !!group.groupDays);
    const specialGroups = this.groups.filter(group => !group.groupDays);

    const sortedRegularGroups = !this.sortColumn || !this.sortDirection
      ? regularGroups
      : [...regularGroups].sort((a, b) => {
        let valueA: string;
        let valueB: string;

        switch (this.sortColumn) {
          case 'level':
            valueA = a.groupLevel;
            valueB = b.groupLevel;
            break;
          case 'day':
            valueA = a.groupDays;
            valueB = b.groupDays;
            break;
          case 'hour':
            valueA = a.groupHours;
            valueB = b.groupHours;
            break;
          case 'lector':
            valueA = a.groupLector;
            valueB = b.groupLector;
            break;
          case 'type':
            valueA = a.groupType;
            valueB = b.groupType;
            break;
          default:
            return 0;
        }

        const comparison = valueA.localeCompare(valueB);
        return this.sortDirection === 'asc' ? comparison : -comparison;
      });

    return [...sortedRegularGroups, ...specialGroups];
  }

  getFormattedGroupDays(groupDays: string): string {
    return this.groupService.getFormattedGroupDays(groupDays);
  }

  getFormattedGroupHours(groupHours: string): string {
    return groupHours.split('$')[0];
  }
}

// src/groups-table/GroupsTable.tsx
import { Group } from "../models/group";
import { getFormattedGroupDays } from "../services/group-service";
import { useState } from "react";

import styles from "./GroupsTable.module.css";

type SortColumn = 'level' | 'day' | 'hour' | 'lector' | 'type' | null;
type SortDirection = 'asc' | 'desc' | null;

export const GroupsTable = ({
  groups,
  onShowGroupDetails,
  onShowSignIn,
  onShowNotify,
}: {
  groups: Group[];
  onShowGroupDetails: (groupId: string) => Promise<void>;
  onShowSignIn: (groupId: string) => Promise<void>;
  onShowNotify: (groupId: string) => Promise<void>;
}) => {
  const [sortColumn, setSortColumn] = useState<SortColumn>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>(null);

  const handleSort = (column: SortColumn) => {
    if (sortColumn === column) {
      if (sortDirection === 'desc') {
        setSortDirection('asc');
      } else if (sortDirection === 'asc') {
        setSortDirection(null);
        setSortColumn(null);
      } else {
        setSortDirection('desc');
      }
    } else {
      setSortColumn(column);
      setSortDirection('desc');
    }
  };

  const getSortedGroups = () => {
    const regularGroups = groups.filter(group => !!group.groupDays);
    const specialGroups = groups.filter(group => !group.groupDays);

    const sortedRegularGroups = !sortColumn || !sortDirection
      ? regularGroups
      : [...regularGroups].sort((a, b) => {
        let valueA: string;
        let valueB: string;

        switch (sortColumn) {
          case 'level':
            valueA = a.groupShortName;
            valueB = b.groupShortName;
            break;
          case 'day':
            valueA = a.groupDays || '';
            valueB = b.groupDays || '';
            break;
          case 'hour':
            valueA = a.groupHours ? a.groupHours.split('$')[0] : '';
            valueB = b.groupHours ? b.groupHours.split('$')[0] : '';
            break;
          case 'lector':
            valueA = a.groupLector;
            valueB = b.groupLector;
            break;
          case 'type':
            valueA = a.groupType;
            valueB = b.groupType;
            break;
          default:
            return 0;
        }

        const compareResult = valueA.localeCompare(valueB);
        return sortDirection === 'asc' ? compareResult : -compareResult;
      });

    return [...sortedRegularGroups, ...specialGroups];
  };

  const renderSortIcon = (column: SortColumn) => {
    if (sortColumn !== column) {
      return null;
    }

    return (
      <span className={`material-symbols-outlined ${styles.sortIcon}`}>
        {sortDirection === 'asc' ? 'arrow_upward' : 'arrow_downward'}
      </span>
    );
  };

  const sortedGroups = getSortedGroups();

  return (
    <div className={styles.groupsTable}>
      <div className={styles.tableHeader}>
        <div
          className={`${styles.firstColumn} ${styles.levelHeader}}`}
          onClick={() => handleSort('level')}
        >
          POZIOM {renderSortIcon('level')}
        </div>
        <div
          className={styles.dayHeader}
          onClick={() => handleSort('day')}
        >
          DZIEŃ {renderSortIcon('day')}
        </div>
        <div
          className={styles.hourHeader}
          onClick={() => handleSort('hour')}
        >
          GODZINA {renderSortIcon('hour')}
        </div>
        <div
          className={styles.lectorHeader}
          onClick={() => handleSort('lector')}
        >
          NAUCZYCIEL {renderSortIcon('lector')}
        </div>
        <div
          className={styles.typeHeader}
          onClick={() => handleSort('type')}
        >
          TRYB {renderSortIcon('type')}
        </div>
        <div className={`${styles.infoHeader} ${styles.nonSortable}`}>INFO</div>
        <div className={`${styles.signInHeader} ${styles.nonSortable}`}></div>
      </div>
      <div className={styles.tableBody}>
        {sortedGroups.map((group) => (
          <div key={group.groupId} className={styles.tableRow}>
            <div className={`${styles.firstColumn} ${styles.level}`}>
              {group.groupFreePlaces === 0 && <div className={styles.fullTag}>Pełna</div>}
              {group.groupShortName}
            </div>
            {!group.groupDays && (
              <>
                <div className={styles.specialRow}>{group.groupLector}</div>
                <div className={styles.type}>
                  <span className={styles.icon}>
                    <span className="material-symbols-outlined">home</span>
                  </span>

                  <span className={styles.icon}>
                    <span className="material-symbols-outlined">computer</span>
                  </span>
                </div>
              </>
            )}
            {group.groupDays && (
              <>
                {" "}
                <div className={styles.day}>
                  {getFormattedGroupDays(group.groupDays)}
                </div>
                <div className={styles.hour}>
                  {group.groupHours.split("$")[0]}
                </div>
                <div className={styles.lector}>{group.groupLector}</div>{" "}
                <div className={styles.type}>
                  {group.groupType === "stacjonarna" ? (
                    <div className={styles.icon}>
                      <span className="material-symbols-outlined">home</span>
                    </div>
                  ) : (
                    <div className={styles.icon}>
                      <span className="material-symbols-outlined">
                        computer
                      </span>
                    </div>
                  )}
                </div>
              </>
            )}

            <div
              className={`${styles.icon} ${styles.infoIcon} ${styles.info}`}
              onClick={() => onShowGroupDetails(group.groupId)}
            >
              <span className="material-symbols-outlined">info</span>
            </div>
            {group.groupFreePlaces === 0 ? (
              <div
                className={`${styles.signInBtn} ${styles.danteButton} ${styles.signIn}`}
                onClick={() => onShowNotify(group.groupId)}
              >
                Powiadom mnie
              </div>
            ) : (
              <div
                className={`${styles.signInBtn} ${styles.danteButton} ${styles.signIn}`}
                onClick={() => onShowSignIn(group.groupId)}
              >
                Zapisz się
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
};
