// angular-groups-list/src/lib/components/group-card/group-card.component.ts
import { Component, Input, Output, EventEmitter, OnInit, AfterViewInit, ViewChild, ElementRef } from '@angular/core';
import { Group } from '../../models/group';
import { GroupService } from '../../services/group.service';

@Component({
  selector: 'dante-group-card',
  template: `
    <div 
      class="group-card" 
      [ngClass]="{ 'full-group-card': group.groupFreePlaces === 0 }"
      [style.width.px]="cardWidth">
      
      <div *ngIf="group.groupFreePlaces === 0" class="group-full-banner">
        Pełna
      </div>
      
      <div class="group-type">{{ group.groupCityOrType }}</div>
      
      <div #groupLevelRef class="group-level">
        {{ group.groupShortName }}
      </div>
      
      <div class="group-days">
        {{ getFormattedGroupDays() }} {{ getFormattedGroupHours() }}
      </div>
      
      <div class="group-lector">{{ group.groupLector }}</div>
      
      <div class="buttons-container">
        <div *ngIf="!isLandingPage"
             class="show-more-btn dante-button info-button"
             (click)="onShowGroupDetails.emit(group.groupId)">
          Info
        </div>
        
        <div *ngIf="group.groupFreePlaces === 0 && !isLandingPage; else signInButton"
             class="sign-in-btn dante-button notify-button"
             (click)="onShowNotify.emit(group.groupId)">
          Powiadom
        </div>
        
        <ng-template #signInButton>
          <div class="sign-in-btn dante-button"
               (click)="onShowSignIn.emit(group.groupId)">
            Zapisz się
          </div>
        </ng-template>
      </div>
    </div>
  `,
  styleUrls: ['./group-card.component.css']
})
export class GroupCardComponent implements OnInit, AfterViewInit {
  @Input() group!: Group;
  @Input() isLandingPage?: boolean = false;
  
  @Output() onShowGroupDetails = new EventEmitter<string>();
  @Output() onShowSignIn = new EventEmitter<string>();
  @Output() onShowNotify = new EventEmitter<string>();

  @ViewChild('groupLevelRef') groupLevelRef!: ElementRef<HTMLDivElement>;

  cardWidth = 230;

  constructor(private groupService: GroupService) {}

  ngOnInit(): void {}

  ngAfterViewInit(): void {
    this.adjustFontSizeIfNeeded();
  }

  getFormattedGroupHours(): string {
    return this.group.groupHours.split('$')[0];
  }

  getFormattedGroupDays(): string {
    return this.groupService.getFormattedGroupDays(this.group.groupDays);
  }

  private adjustFontSizeIfNeeded(): void {
    if (this.groupLevelRef?.nativeElement) {
      const element = this.groupLevelRef.nativeElement;
      const width = element.offsetWidth;
      
      if (width > this.cardWidth) {
        let fontSize = parseFloat(window.getComputedStyle(element).fontSize);
        
        while (element.offsetWidth > this.cardWidth && fontSize > 0) {
          fontSize -= 1;
          element.style.fontSize = `${fontSize}px`;
        }
      }
    }
  }
}

// src/group-card/GroupCard.tsx
import { useEffect, useRef } from "react";
import { Group } from "../models/group";
import { dayMapping } from "../services/group-service";

import styles from "./GroupCard.module.css";

export const GroupCard = ({
  group,
  onShowGroupDetails,
  onShowSignIn,
  onShowNotify,
}: {
  group: Group;
  onShowGroupDetails: (groupId: string) => Promise<void>;
  onShowSignIn: (groupId: string) => Promise<void>;
  onShowNotify: (groupId: string) => Promise<void>;
}) => {
  const groupLevelRef = useRef<HTMLDivElement>(null);
  const cardWidth = 230;

  const getFormattedGroupDays = (groupDays: string): string => {
    return groupDays
      .split("-")
      .map((day) => dayMapping[day] || day)
      .join("-");
  };

  const getFormattedGroupHours = (groupHours: string): string => {
    return groupHours.split("$")[0];
  };

  useEffect(() => {
    if (groupLevelRef.current) {
      const width = groupLevelRef.current.offsetWidth;
      if (width > cardWidth) {
        let fontSize = parseFloat(
          window.getComputedStyle(groupLevelRef.current).fontSize
        );

        while (groupLevelRef.current.offsetWidth > cardWidth && fontSize > 0) {
          fontSize -= 1;
          groupLevelRef.current.style.fontSize = `${fontSize}px`;
        }
      }
    }
  }, []);

  return (
    <div className={styles.groupCard} style={{ width: `${cardWidth}px` }}>
      {group.groupFreePlaces === 0 && (
        <div className={styles.groupFullBanner}>Pełna</div>
      )}
      <div className={styles.groupType}>{group.groupType}</div>
      <div className={styles.groupLevel} ref={groupLevelRef}>
        {group.groupShortName}
      </div>
      <div className={styles.groupDays}>
        {getFormattedGroupDays(group.groupDays)}{" "}
        {getFormattedGroupHours(group.groupHours)}
      </div>
      <div className={styles.groupLector}>{group.groupLector}</div>
      <div className={styles.buttonsContainer}>
        <div
          className={`${styles.showMoreBtn} ${styles.danteButton} ${styles.infoButton}`}
          onClick={() => onShowGroupDetails(group.groupId)}
        >
          Info
        </div>
        {group.groupFreePlaces === 0 ? (
          <div
            className={`${styles.signInBtn} ${styles.danteButton} ${styles.notifyButton}`}
            onClick={() => onShowNotify(group.groupId)}
          >
            Powiadom
          </div>
        ) : (
          <div
            className={`${styles.signInBtn} ${styles.danteButton}`}
            onClick={() => onShowSignIn(group.groupId)}
          >
            Zapisz się
          </div>
        )}
      </div>
    </div>
  );
};
